spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
          - Path=/api/v1/first/**
        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
          - Path=/api/v2/second/**
      global-filter:
        load-balancer-client:
          enabled: true
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: false
