spring:
  application:
    name: first-service
server:
  port: ${app-port:9090}
  servlet:
    context-path: /api/v1/first/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
